// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7cIj6FFXrUixw1byCG-4mmfx-fVTvhg',
    appId: '1:751857306179:web:613a9eb2949527997a22f6',
    messagingSenderId: '751857306179',
    projectId: 'habilita-enem',
    authDomain: 'habilita-enem.firebaseapp.com',
    storageBucket: 'habilita-enem.appspot.com',
    measurementId: 'G-LN1B29G38C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATE3Nc54Yk4OqPSlhTl1xLq_kCOhjXLN8',
    appId: '1:751857306179:android:75e027e36c8916c07a22f6',
    messagingSenderId: '751857306179',
    projectId: 'habilita-enem',
    storageBucket: 'habilita-enem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuz-ETQVO7qqX1456jUJTIe3f2RT2ZDwc',
    appId: '1:751857306179:ios:7fef7376b16176b87a22f6',
    messagingSenderId: '751857306179',
    projectId: 'habilita-enem',
    storageBucket: 'habilita-enem.appspot.com',
    iosClientId: '751857306179-sr2db9u9lqufdnip9qkslkf4dosr8vum.apps.googleusercontent.com',
    iosBundleId: 'com.gcapps.habilitaenem.habilitaEnem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuz-ETQVO7qqX1456jUJTIe3f2RT2ZDwc',
    appId: '1:751857306179:ios:7fef7376b16176b87a22f6',
    messagingSenderId: '751857306179',
    projectId: 'habilita-enem',
    storageBucket: 'habilita-enem.appspot.com',
    iosClientId: '751857306179-sr2db9u9lqufdnip9qkslkf4dosr8vum.apps.googleusercontent.com',
    iosBundleId: 'com.gcapps.habilitaenem.habilitaEnem',
  );
}
